# Generated by Django 2.2 on 2021-07-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
