# Generated by Django 2.2 on 2021-06-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner')),
                ('title1', models.CharField(max_length=250)),
                ('title2', models.CharField(max_length=300)),
            ],
        ),
    ]
